plugins:
  - babel
env:
  node: true
  mocha: true
parser: babel-eslint
extends:
  - 'airbnb-base'
rules:
  no-console: 0
  class-methods-use-this: 0
  import/no-extraneous-dependencies: ["error", {"devDependencies": ['./src/tests/**']}]
  no-underscore-dangle: ["error", { "allow": ["_id"] }]
